Repository expo/examples, pull requests merged in 2020-05, with the labels that each got.

#149 Delete unused app.json files
  contributing.md
  with-animated-splash-screen/app.json
  with-auth0/app.json
  with-custom-font/App.js
  with-custom-font/app.json
  with-electron/app.json
  with-facebook-auth/app.json
  with-firebase-storage-upload/app.json
  with-formdata-image-upload/app/app.json
  with-gatsby/app.json
  with-google-vision/app.json
  with-icons/app.json
  with-nextjs/app.json
  with-preact/app.json
  with-react-router/app.json
  with-socket-io/app/app.json
  with-sqlite/app.json
  with-storybook/app.json
  with-twitter-auth/app/app.json
  with-typescript/app.json
  with-victory-native/app.json
  with-video-background/app.json
  with-web-in-react-native-community-cli/app.json
  with-webbrowser-redirect/app/app.json
  with-webbrowser-redirect/app/package.json
Labels: enhancement

#150 Use app.config.js
  contributing.md
  with-animated-splash-screen/app.config.js
  with-animated-splash-screen/app.json
  with-electron/app.json
  with-gatsby/README.md
  with-postpublish-hooks/README.md
  with-postpublish-hooks/app.config.js
  with-postpublish-hooks/app.json
  with-storybook/README.md
  with-victory-native/app.config.js
  with-victory-native/app.json
  with-web-in-react-native-community-cli/README.md
  with-webbrowser-redirect/app/app.config.js
  with-webbrowser-redirect/app/app.json
Labels: enhancement

#154 Update victory native example to use hooks
  with-victory-native/App.js
  with-victory-native/README.md
  with-victory-native/app.config.js
  with-victory-native/package.json
Labels: enhancement

#159 [auth0] Updated to new auth-session API
  with-auth0/App.js
  with-auth0/README.md
  with-auth0/package.json
  with-twitter-auth/README.md
Labels: enhancement

#160 Created three.js example
  with-three/App.tsx
  with-three/README.md
  with-three/babel.config.js
  with-three/icon.jpg
  with-three/package.json
  with-three/tsconfig.json
Labels: New Example

#161 Created styled-components example
  with-styled-components/App.js
  with-styled-components/README.md
  with-styled-components/package.json
Labels: New Example

#165 add with-tailwind example
  with-tailwind/App.js
  with-tailwind/README.md
  with-tailwind/package.json
Labels: New Example

#171 add with-drawer-navigation example
  with-drawer-navigation/App.js
  with-drawer-navigation/README.md
  with-drawer-navigation/babel.config.js
  with-drawer-navigation/package.json
Labels: New Example, enhancement

#173 Created blank example
  blank/App.js
  blank/README.md
  blank/babel.config.js
  blank/package.json
  contributing.md
Labels: New Example
